### PR TITLE
truncate runDir path name

### LINKED ISSUE #67: `unix socket path too long` error when using action in self-hosted runner
### Behaviour

When using the action with the below config on a self-hosted runner the action fails with the error:

```
containerd: failed to get listener for debug endpoint: "/home/runner/setup-docker-action-b5a3e375-d6e3-40d4-91f8-bce26addece7/execroot/containerd/containerd-debug.sock": unix socket path too long (> 104)
```

This only happens in self-hosted runners hosted by [runs-on ](https://runs-on.com/), in Github hosted runners it works just fine.

I suspect [this](https://github.com/crazy-max/ghaction-setup-docker/blob/fdc6583d4ef3119263df3193b0480bd05ff270e6/src/main.ts#L16) is offending line of code, it uses a `uuid.v4` to generate the path name which makes the socket path too long in certain circumstances. A suggestion would be to truncate the UUID to 8 characters to shorten the path length significantly (assuming a unique path name is required at all).

#### Steps to reproduce this issue

1. Use a `runs-on` hosted runner
2. Use the action

#### Expected behaviour

Setup docker without exiting with errors

#### Actual behaviour

The action exited with error code `1`

### Configuration

The repository and workflow is private
[3_Build and push api to ECR.txt](https://github.com/crazy-max/ghaction-setup-docker/files/15074421/3_Build.and.push.api.to.ECR.txt)

```yml
- uses: crazy-max/ghaction-setup-docker@v2
  with:
    daemon-config: |
      {
        "features": {
          "containerd-snapshotter": true
        }
      }
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs)
> and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

### PR DESCRIPTION
**Pull request by MatthewCane**
Fix #67 by reducing the runDir directory name from 57 characters to 29 charaters, preventing the socket path from being more than the maximum of 104 charaters on Unix based systems.

### CODE REVIEW

**Review by crazy-max — CHANGES_REQUESTED** [review]
Can you remove the issue number from your commit message otherwise it would spam the issue with messages on rebase, thanks!

**Comment by MatthewCane** [comment]
@crazy-max I've amended the commit message

**Review by crazy-max — CHANGES_REQUESTED** [review]
You also need to run `docker buildx bake pre-checkin` to generate dist, see https://github.com/crazy-max/ghaction-setup-docker/blob/master/.github/CONTRIBUTING.md#submitting-a-pull-request

Commit example `chore: update generated content`: https://github.com/crazy-max/ghaction-setup-docker/pull/58/commits

**Comment by MatthewCane** [comment]
Thanks for the pointers! I've followed the guide but I am getting the following error when running `docker buildx bake validate`: `'ERROR: Build result differs. Please build first with "docker buildx bake build"'`.

I've tried running `docker buildx bake build` as well as removing everything and going through the steps again but I am still getting the error.

I have commited the new `dist` files anyway, just so you can see what it comes out with but I will amend that commit if I can get the validate step to complete successfully.

**Comment by crazy-max** [comment]
> Thanks for the pointers! I've followed the guide but I am getting the following error when running `docker buildx bake validate`: `'ERROR: Build result differs. Please build first with "docker buildx bake build"'`.

Thanks, did you commit before running `validate`? This might be related but I will take a look.

**Review by crazy-max — APPROVED** [review]
LGTM thanks!

**Pull request merged**
